python3 main_continual.py \
    --dataset imagenet100 \
    --encoder resnet18 \
    --data_dir $DATA_DIR \
    --train_dir IN-100/train \
    --val_dir IN-100/val \
    --split_strategy class \
    --max_epochs 500 \
    --num_tasks 5 \
    --task_idx 0 \
    --gpus 0 \
    --num_workers 4 \
    --precision 16 \
    --optimizer sgd \
    --scheduler warmup_cosine \
    --lr 0.4 \
    --weight_decay 1e-4 \
    --batch_size 128 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --gaussian_prob 1.0 0.1 \
    --solarization_prob 0.0 0.2 \
    --dali \
    --check_val_every_n_epoch 9999 \
    --name barlow-in100x5-pfr-lamb:$DSTL_LAMB-seed:$SEED \
    --wandb \
    --save_checkpoint \
    --method barlow_twins \
    --proj_hidden_dim 2048 \
    --output_dim 2048 \
    --scale_loss 0.1 \
    --task_aware_knn \
    --distiller pfr \
    --distill_lamb $DSTL_LAMB \
    --distill_proj_hidden_dim 256 \
    --seed $SEED
