python3 main_continual.py \
    --dataset imagenet100 \
    --encoder resnet18 \
    --data_dir $DATA_DIR \
    --train_dir IN-100/train \
    --val_dir IN-100/val \
    --split_strategy class \
    --max_epochs 100 \
    --num_tasks 5 \
    --task_idx 0 \
    --gpus 0 \
    --num_workers 4 \
    --precision 16 \
    --optimizer sgd \
    --scheduler warmup_cosine \
    --lr 0.1 \
    --weight_decay 1e-4 \
    --batch_size 64 \
    --min_scale 0.9 \
    --brightness 0.0 \
    --contrast 0.0 \
    --saturation 0.0 \
    --hue 0.0 \
    --gaussian_prob 0.0 0.0 \
    --solarization_prob 0.0 0.0 \
    --grayscale_prob 0.0 \
    --dali \
    --check_val_every_n_epoch 9999 \
    --name supervised-base-in100x5-seed:$SEED \
    --wandb \
    --save_checkpoint \
    --method supervised \
    --task_aware_knn \
    --seed $SEED
